### ISSUE TITLE
use tripleo-ansible-inventory

### ISSUE THREAD

**Issue by fultonj** [fultonj/tripleo-ceph-ansible#7]
Flavio gave us support for `ansible-playbook -i` in [mistral-ansible-actions](https://github.com/d0ugal/mistral-ansible-actions/pull/8). By way of tripleo-validations we already ship an undercloud with an [a dynamic overcloud inventory](https://github.com/openstack/tripleo-validations/blob/master/scripts/tripleo-ansible-inventory). By way of a simple playbook [1], I can use the dynamic inventory to reach controllers or computes [2]. I can easily modify mistral-ceph-ansible.yaml to use this, but I need a way to tell it which hosts are the mons, osds, [and so on](https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample). I could see about setting an alias in the short run OR propose a change to [the existing inventory script](https://github.com/openstack/tripleo-validations/blob/master/scripts/tripleo-ansible-inventory) so that it deduces which host should be a mon or osd from the deployment plan (because a user could compose any role). OR if I can get the alias working, then I might have mistral-ceph-ansible.yaml hook into the deployment plan to see which node has which service. 

[1]
```
(undercloud) [stack@undercloud ~]$ cat ping.yml
---
- hosts: compute
  gather_facts: no
  tasks:
  - name: ping computes
    ping:

- hosts: controller
  gather_facts: no
  tasks:
  - name: ping controllers
    ping:
(undercloud) [stack@undercloud ~]$ 
```

[2]
```
(undercloud) [stack@undercloud ~]$ ansible-playbook ping.yml -i /usr/bin/tripleo-ansible-inventory

PLAY [compute] *****************************************************************

TASK [ping computes] ***********************************************************
ok: [192.168.24.12]

PLAY [controller] **************************************************************

TASK [ping controllers] ********************************************************
ok: [192.168.24.10]

PLAY RECAP *********************************************************************
192.168.24.10              : ok=1    changed=0    unreachable=0    failed=0   
192.168.24.12              : ok=1    changed=0    unreachable=0    failed=0   

(undercloud) [stack@undercloud ~]$
```

**Comment by fultonj** [comment]
The ansible inventory for tripleo-validations only groups for controllers and computes based on the name "compute" or "control" in the Heat stack. It does not seem to be able to reach any composed role that might contain any ceph service and could only make ceph changes to HCI controllers or computes. 

 https://github.com/openstack/tripleo-validations/blob/master/scripts/tripleo-ansible-inventory#L150-L165

**Comment by fultonj** [comment]
If the tripleo-validations group is interested in expanding the tripleo-ansible-inventory as described in the following RFE then I should help solve this problem there. 

https://bugs.launchpad.net/tripleo/+bug/1685544

**Comment by fultonj** [comment]
As per a conversation w/ gfidente shardy and flapper87 and given the timing issue with triple-ansible-inventory [1], I will instead solve this using a different method. The Heat resource that will start the Mistral workflow will continue to pass the IP lists for mons, osds, etc [2] and the mistral workflow itself will use this to build the inventory. As all the necessary information will be passed as arguments this should be easy as I will use the new -i option [3]. However, I see that ansible-playbook's -i option can take a few options, but i haven't found a way to get the group name that ceph-ansbile expects in one call. Thus, the Mistral workflow will ensure there exists a temporary file created from the arguments before running the playbook and then pass that temporary file with the -i option. 

[1] https://review.openstack.org/#/c/457972/
[2] https://review.openstack.org/#/c/458058/2/extraconfig/tasks/ceph-ansible-workflow.j2.yaml 
[3] https://github.com/d0ugal/mistral-ansible-actions/pull/8

**Comment by fultonj** [comment]
This is now in pretty decent shape: 
```
 tasks:
    ceph_install:
      action: ansible-playbook
      input:
        inventory:
          mons:
            hosts:
              "{% for ip in env().service_ips.ceph_mon_ctlplane_node_ips %}{{ ip }}{% endfor%}"
          osds:
            hosts:
              "{% for ip in env().service_ips.ceph_osd_ctlplane_node_ips %}{{ ip }}{% endfor %}"
        playbook: /usr/share/ceph-ansible/site.yml.sample
```
Just need to:
- add conditional to not try to loop if `env().service_ips.ceph_FOO_ctlplane_node_ips` is empty
- add loops for other types: https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L42-L105
